"""actualizando schemas

Revision ID: 1fd620d9c01a
Revises: f18a77b3240e
Create Date: 2026-04-14 19:35:46.299245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fd620d9c01a'
down_revision: Union[str, None] = 'f18a77b3240e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrica_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('transporte_id', sa.Integer(), nullable=True),
    sa.Column('tiempo_minutos', sa.Integer(), nullable=False),
    sa.Column('costo_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comision_plataforma', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('distancia_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnico.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transporte_id'], ['transporte.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrica_servicio_cliente_id'), 'metrica_servicio', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_metrica_servicio_incidente_id'), 'metrica_servicio', ['incidente_id'], unique=True)
    op.create_index(op.f('ix_metrica_servicio_solicitud_id'), 'metrica_servicio', ['solicitud_id'], unique=True)
    op.create_index(op.f('ix_metrica_servicio_taller_id'), 'metrica_servicio', ['taller_id'], unique=False)
    op.create_table('tecnico_ubicacion',
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('precision_metros', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tecnico_id')
    )
    op.create_index(op.f('ix_tecnico_ubicacion_solicitud_id'), 'tecnico_ubicacion', ['solicitud_id'], unique=False)
    op.execute('DROP TABLE IF EXISTS metrica CASCADE')
    op.execute('DROP TABLE IF EXISTS comision CASCADE')
    op.execute('DROP TABLE IF EXISTS tecnico_servicio CASCADE')
    op.execute('DROP TABLE IF EXISTS pago CASCADE')
    pass # op.create_index(op.f('ix_evidencia_incidente_id'), 'evidencia', ['incidente_id'], unique=False)
    op.add_column('historial', sa.Column('taller_id', sa.Integer(), nullable=True))
    op.add_column('historial', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.alter_column('historial', 'incidente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_historial_cliente_id'), 'historial', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_historial_incidente_id'), 'historial', ['incidente_id'], unique=False)
    op.create_index(op.f('ix_historial_taller_id'), 'historial', ['taller_id'], unique=False)
    op.create_foreign_key(None, 'historial', 'taller', ['taller_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'historial', 'cliente', ['cliente_id'], ['id'], ondelete='CASCADE')
    op.add_column('incidente', sa.Column('info_reintentos', sa.SmallInteger(), server_default='0', nullable=False))
    op.create_index(op.f('ix_incidente_cliente_id'), 'incidente', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_incidente_vehiculo_placa'), 'incidente', ['vehiculo_placa'], unique=False)
    op.add_column('solicitud', sa.Column('tecnico_id', sa.Integer(), nullable=True))
    op.add_column('solicitud', sa.Column('transporte_id', sa.Integer(), nullable=True))
    op.add_column('solicitud', sa.Column('comentario', sa.Text(), nullable=True))
    op.create_index(op.f('ix_solicitud_incidente_id'), 'solicitud', ['incidente_id'], unique=False)
    op.create_index(op.f('ix_solicitud_taller_id'), 'solicitud', ['taller_id'], unique=False)
    op.create_foreign_key(None, 'solicitud', 'transporte', ['transporte_id'], ['id'])
    op.create_foreign_key(None, 'solicitud', 'tecnico', ['tecnico_id'], ['id'])
    op.drop_column('solicitud', 'tiempo_respuesta')
    op.add_column('tecnico', sa.Column('taller_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tecnico_taller_id'), 'tecnico', ['taller_id'], unique=False)
    op.create_foreign_key(None, 'tecnico', 'taller', ['taller_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_transporte_taller_id'), 'transporte', ['taller_id'], unique=False)
    op.drop_constraint('usuario_correo_key', 'usuario', type_='unique')
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_vehiculo_cliente_id'), 'vehiculo', ['cliente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculo_cliente_id'), table_name='vehiculo')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.create_unique_constraint('usuario_correo_key', 'usuario', ['correo'])
    op.drop_index(op.f('ix_transporte_taller_id'), table_name='transporte')
    op.drop_constraint(None, 'tecnico', type_='foreignkey')
    op.drop_index(op.f('ix_tecnico_taller_id'), table_name='tecnico')
    op.drop_column('tecnico', 'taller_id')
    op.add_column('solicitud', sa.Column('tiempo_respuesta', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'solicitud', type_='foreignkey')
    op.drop_constraint(None, 'solicitud', type_='foreignkey')
    op.drop_index(op.f('ix_solicitud_taller_id'), table_name='solicitud')
    op.drop_index(op.f('ix_solicitud_incidente_id'), table_name='solicitud')
    op.drop_column('solicitud', 'comentario')
    op.drop_column('solicitud', 'transporte_id')
    op.drop_column('solicitud', 'tecnico_id')
    op.drop_index(op.f('ix_incidente_vehiculo_placa'), table_name='incidente')
    op.drop_index(op.f('ix_incidente_cliente_id'), table_name='incidente')
    op.drop_column('incidente', 'info_reintentos')
    op.drop_constraint(None, 'historial', type_='foreignkey')
    op.drop_constraint(None, 'historial', type_='foreignkey')
    op.drop_index(op.f('ix_historial_taller_id'), table_name='historial')
    op.drop_index(op.f('ix_historial_incidente_id'), table_name='historial')
    op.drop_index(op.f('ix_historial_cliente_id'), table_name='historial')
    op.alter_column('historial', 'incidente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('historial', 'cliente_id')
    op.drop_column('historial', 'taller_id')
    op.drop_index(op.f('ix_evidencia_incidente_id'), table_name='evidencia')
    op.create_table('pago',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pago_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('incidente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('metodo', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fecha_hora', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], name='pago_incidente_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pago_pkey'),
    sa.UniqueConstraint('incidente_id', name='pago_incidente_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tecnico_servicio',
    sa.Column('tecnico_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('servicio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], name='tecnico_servicio_servicio_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnico.id'], name='tecnico_servicio_tecnico_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tecnico_id', 'servicio_id', name='tecnico_servicio_pkey')
    )
    op.create_table('comision',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pago_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('porcentaje', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('10.00'), autoincrement=False, nullable=False),
    sa.Column('monto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], name='comision_pago_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='comision_pkey'),
    sa.UniqueConstraint('pago_id', name='comision_pago_id_key')
    )
    op.create_table('metrica',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incidente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tiempo_llegada', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.Column('tiempo_respuesta', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.Column('tiempo_resolucion', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.Column('puntuacion', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('fecha_hora', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], name='metrica_incidente_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='metrica_pkey'),
    sa.UniqueConstraint('incidente_id', name='metrica_incidente_id_key')
    )
    op.drop_index(op.f('ix_tecnico_ubicacion_solicitud_id'), table_name='tecnico_ubicacion')
    op.drop_table('tecnico_ubicacion')
    op.drop_index(op.f('ix_metrica_servicio_taller_id'), table_name='metrica_servicio')
    op.drop_index(op.f('ix_metrica_servicio_solicitud_id'), table_name='metrica_servicio')
    op.drop_index(op.f('ix_metrica_servicio_incidente_id'), table_name='metrica_servicio')
    op.drop_index(op.f('ix_metrica_servicio_cliente_id'), table_name='metrica_servicio')
    op.drop_table('metrica_servicio')
    # ### end Alembic commands ###
